#! /bin/sh
# -*- mode: scheme; coding: utf-8 -*-
exec guile -e main -s "$0" "$@"
!#


;;;;
;;;; Copyright (C) 2023 - 2026
;;;; Free Software Foundation, Inc.

;;;; This file is part of GNU G-Golf

;;;; GNU G-Golf is free software; you can redistribute it and/or modify
;;;; it under the terms of the GNU Lesser General Public License as
;;;; published by the Free Software Foundation; either version 3 of the
;;;; License, or (at your option) any later version.

;;;; GNU G-Golf is distributed in the hope that it will be useful, but
;;;; WITHOUT ANY WARRANTY; without even the implied warranty of
;;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;;;; Lesser General Public License for more details.

;;;; You should have received a copy of the GNU Lesser General Public
;;;; License along with GNU G-Golf.  If not, see
;;;; <https://www.gnu.org/licenses/lgpl.html>.
;;;;

;;; Commentary:

;; This example uses the (demos nuclear-icon) module, which implements
;; the nuclear icon snapshot either using gsk (the default), or cairo
;; (if you pass the -c or --cairo option on the command line).
;;
;; The cairo snapshot version requires guile-cairo, a patched verison of
;; guile-cairo actually. Guile-cairo is here:

;;	https://www.nongnu.org/guile-cairo/

;; As said above, it actually needs a patched version of guile-cairo,
;; that contains the following new interface (which is not in
;; guile-cairo 1.11.2):

;;	cairo-pointer->context

;; If by the time you have access to and wish to try this example
;; guile-cairo hasn't been released and/or cairo-pointer->context still
;; isn't commited to the latest guile-cairo repository master branch,
;; get in touch with us on irc.libera.chat, channel #guile, or by email,
;; we'll guide you to manually patch your local version.

;;; Code:


(eval-when (expand load eval)
  (use-modules (oop goops))

  (default-duplicate-binding-handler
    '(merge-generics replace warn-override-core warn last))

  (use-modules (g-golf))

  (g-irepository-require "Gtk" #:version "4.0")
  (for-each (lambda (name)
              (gi-import-by-name "Gdk" name))
      '("Paintable"))

  (for-each (lambda (name)
              (gi-import-by-name "Gtk" name))
      '("Application"
        "ApplicationWindow"
        "Picture")))

(add-to-load-path (dirname (current-filename)))
(use-modules (demos nuclear-icon))


(define (activate app)
  (let ((window (make <gtk-application-window>
                  #:title "Nuclear Icon"
                  #:default-width 300
                  #:default-height 200
                  #:application app))
        (nuclear (make <nuclear-icon> #:rotation 0.0))
        (picture (make <gtk-picture>)))
    (set-paintable picture nuclear)
    (set-child window picture)
    (present window)))


(define (main args)
  (let* ((debug? (or (member "-d" args)
                     (member "--debug" args)))
         (cairo? (or (member "-c" args)
                     (member "--cairo" args)))
         (app (make <gtk-application>
                #:application-id "org.gtk.example"))
         (animate
          (lambda ()
            (connect app 'activate activate)
            (let ((status (run app '())))
              (exit status)))))
    (cond ((and debug? cairo?)
           (parameterize ((%debug #t) (%cairo? #t))
             (animate)))
          (debug?
           (parameterize ((%debug #t))
             (animate)))
          (cairo?
           (parameterize ((%cairo? #t))
             (animate)))
          (else
           (animate)))))
