@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 - 2022 Free Software Foundation, Inc.
@c See the file g-golf.texi for copying conditions.


@defindex ct


@node Common Types
@subsection Common Types

G-Golf Common Types low level API.@*
common types - TODO


@subheading Procedures

@indentedblock
@table @code
@item @ref{g-type-tag-to-string}
@end table
@end indentedblock


@subheading Types and Values

@indentedblock
@table @code
@item @ref{%gi-type-tag}
@item @ref{%gi-array-type}
@end table
@end indentedblock


@subheading Procedures


@anchor{g-type-tag-to-string}
@deffn Procedure g-type-tag-to-string type-tag

Returns a string or @code{#f}.

Obtains the string representation for @var{type-tag} or @code{#f} if it
does not exist (note that in this case, the upstream function returns
@code{"unknown"}).

@var{type-tag} can either be an @code{id} or a @code{symbol}, a member
of the @code{enum-set} of @ref{%gi-type-tag}.
@end deffn


@subheading Types and Values


@anchor{%gi-type-tag}
@defivar <gi-enum> %gi-type-tag

An instance of @code{<gi-enum>}, who's members are the type tag of
a @code{GITypeInfo}:


@indentedblock
@emph{g-name}: GITypeTag  @*
@emph{name}: gi-type-tag @*
@emph{enum-set}:
@indentedblock
void		@*
boolean		@*
int8		@*
uint8		@*
int16		@*
uint16		@*
int32		@*
uint32		@*
int64		@*
uint64		@*
float		@*
double		@*
gtype		@*
utf8		@*
filename	@*
array		@*
interface	@*
glist		@*
gslist		@*
ghash		@*
error		@*
unichar		
@end indentedblock
@end indentedblock
@end defivar


@anchor{%gi-array-type}
@defivar <gi-enum> %gi-array-type

An instance of @code{<gi-enum>}, who's members are the type of array in
a @code{GITypeInfo}:


@indentedblock
@emph{g-name}: GIArrayType  @*
@emph{name}: gi-array-type @*
@emph{enum-set}:
@indentedblock
c		@*
array		@*
ptr-array	@*
byte-array
@end indentedblock
@end indentedblock
@end defivar
