@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 - 2022 Free Software Foundation, Inc.
@c See the file g-golf.texi for copying conditions.


@node Utilities_
@subsection Utilities


@subheading Procedures

@indentedblock
@table @code
@item @ref{g-studly-caps-expand}
@item @ref{g-name->name}
@item @ref{g-name->short-name}
@item @ref{g-name->class-name}
@item @ref{gi-type-tag->ffi}
@item @ref{gi-type-tag->init-val}
@item @ref{syntax-name->method-name}
@end table
@end indentedblock


@subheading Variables

@indentedblock
@table @code
@item @ref{%syntax-name-protect-prefix}
@item @ref{%syntax-name-protect-postfix}
@item @ref{%syntax-name-protect-renamer}
@end table
@end indentedblock


@subheading Description

G-Golf utilities low level API.@*


@subheading Procedures


@anchor{g-studly-caps-expand}
@deffn Procedure g-studly-caps-expand str

Returns a string@footnote{This procedure, as well as @ref{g-name->name}
and @ref{g-name->class-name} come from @uref{@value{UGG}, Guile-GNOME},
where there are named @code{GStudlyCapsExpand},
@code{gtype-name->scm-name} and @code{gtype-name->class-name}.@*@*In
G-Golf, these procedures are also be used to transform other (GObject
Introspection) names, such as function names, hence they use the
@code{g-name->} prefix instead}.

Expand the StudlyCaps @var{str} to a more schemey-form, according to the
conventions of GLib libraries. For example:

@lisp
(g-studly-caps-expand "GStudlyCapsExpand")
@result{} "g-studly-caps-expand"

(g-studly-caps-expand "GSource")
@result{} "g-source"

(g-studly-caps-expand "GtkIMContext")
@result{} "im-context"
@end lisp

G-Golf slightly modified the original code to also allow the possibility
to specially treat the @var{str} (expanded) tokens, such as:

@lisp
(g-studly-caps-expand "WebKitWebContext")
@result{} "webkit-web-context" ;; not "web-kit-web-context"
@end lisp

The list of StudlyCaps token exception pairs are maintained in the
@ref{g-studly-caps-expand-token-exception} alist.
@end deffn


@anchor{g-name->name}
@anchor{g-name->short-name}
@anchor{g-name->class-name}
@deffn Procedure g-name->name g-name [as-string? #f]
@deffnx Procedure g-name->short-name g-name g-parent-name [as-string? #f]
@deffnx Procedure g-name->class-name g-name [as-string? #f]

Return a symbol name, or a string name if @var{as-string} is #t.

@ref{g-name->name} first obtains the scheme representation string for
@var{g-name}, by looking for a possible entry in
@ref{g-name-transform-exception}, or if it failed, by calling
@ref{g-studly-caps-expand}.

If the optional @var{as-string} argument is #t, it returns
that string, otherwise, it calls and returns the result of
@code{string->symbol}.

@ref{g-name->short-name} returns a (method) short name for
@var{g-name}. It first obtains the scheme representation string for both
argument, @var{name} and @var{parent-name}, which is the container
(class) name, then:

@itemize
@item
if @var{parent-name} is (fully) contained in @var{name}, it drops the
@var{parent-name} prefix - or its plural form - and its trailing #\-
(hiphen) delimiter from @var{name};
@ifhtml
@*@*
@end ifhtml

@item
otherwise, it drops the longest common string prefix it finds.
@end itemize

If the optional @var{as-string} argument is #t, it returns
that string, otherwise, it calls and returns the result of
@code{string->symbol}.

To illustrate, here is an example for each of the three above exposed
cases:

@lisp
(g-name->shortname "gdk_event_get_event_type" "GdkEvent")
@result{} get-event-type

(g-name->shortname "gdk_events_get_angle" "GdkEvent")
@result{} get-angle

(g-name->short-name "gtk_drag_begin" "GtkWidget")
@result{} drag-begin
@end lisp

@ref{g-name->class-name} calls @ref{g-name->name}, surrounds the result
using @code{#\<} and @code{#\>} characters then either return that
string, if @var{as-string?} is @code{#t}, otherwise it calls and returns
the result of @code{string->symbol}:

@lisp
(g-name->class-name "GtkWindow")
@result{} <gtk-window>
@end lisp
@end deffn


@anchor{gi-type-tag->ffi}
@deffn Procedure gi-type-tag->ffi type-tag

Returns an integer or @code{'*} (the symbol @code{*}).

Obtains the correponding Guile's ffi tag value for @var{type-tag}, which
must be a member of @ref{%gi-type-tag}.  If @var{type-tag} is unknown,
an exception is raised. Note that Guile's ffi tag values are integers or
@code{'*} (the symbol @code{*}, used by convention to denote pointer
types.
@end deffn


@anchor{gi-type-tag->init-val}
@deffn Procedure gi-type-tag->init-val type-tag

Returns the default init value for @var{type-tag}.

Obtains and returns the default init value for @var{type-tag}, which
will either be @code{0} (zero), or @code{%null-pointer}.
@end deffn


@anchor{syntax-name->method-name}
@deffn Procedure syntax-name->method-name name

Returns a (symbol) name.

This procedure is used to @samp{protect} syntax names, from being
redefined as generic functions and methods.

Users should normally not call this procedure - except for testing
purposes, if/when they customize its default settings - it is
appropriately and automatically called by G-Golf when importing a GI
typelib.

Unless otherwise specified (@pxref{Customization Square} - @emph{GI
Method Short Name Skip}), as it imports a GI typelib, G-Golf creates a
method short name for each imported method, obtained by dropping the
container name (and its trailing hyphen) from the GI typelib method long
name.

GI methods are added to their respective generic function, which is
created if it does not already exist. When a generic function is
created, G-Golf checks if the name is used, and when it is bound to a
procedure, the procedure is 'captured' into an unspecialized method,
which is added to the newly created generic function.

However, when the name is used but its variable value is a syntax, the
above can't be done and the name must be @samp{protected}, which is what
@ref{syntax-name->method-name} does, using a renamer, or by adding a
prefix, a postfix or both to its (symbol) @var{name} argument.

By default, the renamer (@ref{%syntax-name-protect-renamer}) and prefix
(@ref{%syntax-name-protect-prefix}) variables are set to @code{#f}. The
the postfix (@ref{%syntax-name-protect-postfix}) variable is set to
@code{_} (the underscore symbol).

As an example, using these default settings, the method short name for
@code{gcr-secret-exchange-begin} would be @code{begin_}.

@c If the @code{(ice-9 receive)} has also been imported, then the short
@c name method for @code{gcr-secret-exchange-receive} would be
@c @code{receive_}, otherwise, since there would be no syntax name
@c @samp{clash}, it would be @code{receive}.
@end deffn


@subheading Variables


@anchor{%syntax-name-protect-prefix}
@anchor{%syntax-name-protect-postfix}
@anchor{%syntax-name-protect-renamer}
@defvar %syntax-name-protect-prefix
@defvarx %syntax-name-protect-postfix
@defvarx %syntax-name-protect-renamer

These variables are used by @ref{syntax-name->method-name} and may be
customized. Their default values are:

@indentedblock
@table @var
@item %syntax-name-protect-prefix #f
@item %syntax-name-protect-postfix '_ (the underscore symbol)
@item %syntax-name-protect-renamer #f
@end table
@end indentedblock

@var{%syntax-name-protect-prefix} and @var{%syntax-name-protect-postfix}
may be defined as @code{#f} or a symbol name. Unless a renamer is set,
at least one of these two variables must be defined as a symbol name.

The @var{%syntax-name-protect-renamer} may be defined as @code{#f} or a
procedure, that takes one argument - a symbol name - and returns a
symbol name.

@ref{syntax-name->method-name} first checks for a
@var{%syntax-name-protect-renamer}, and calls it if it has been defined,
igoring the other variables.

Otherwise, @ref{syntax-name->method-name} returns a symbol name prefixed
using @var{%syntax-name-protect-prefix} when not @code{#f} and/or
postfixed using @var{%syntax-name-protect-postfix} when not @code{#f}.
As mentioned above, unless a renamer is set, at least one of these two
variables must be defined as a symbol name.
@end defvar
