@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2022 Free Software Foundation, Inc.
@c See the file g-golf.texi for copying conditions.


@node G-Golf Valley
@section G-Golf Valley


@menu
* Cache Park:: Accessing G-Golf caches.
* Customization Square:: G-Golf customization functionality.
@end menu


@include ug-ggv-cache.texi
@include ug-ggv-customization.texi
